### ISSUE TITLE
The EU status bar component is hidden by the system

### ISSUE THREAD

**Issue by zxitedu** [gao-sun/eul#119]
<img width="296" alt="iShot2020-12-01 10 14 33" src="https://user-images.githubusercontent.com/48445631/100688872-420ec880-33be-11eb-89f1-50a3cdff07b6.png">
When you open a full screen window without the above menu bar (such as the remote win system), such a prompt will appear. If you ignore the prompt, it will pop up all the time. I hope you can cancel this pop-up window. Thank you(在打开没有上面菜单栏的全屏窗口的时候(比如远程win系统)会出现这样的提示并且忽略也会一直弹窗提示，希望把这个弹窗可以取消掉 谢谢在打开没有上面菜单栏的全屏窗口的时候(比如远程win系统)会出现这样的提示并且忽略也会一直弹窗提示，希望把这个弹窗可以取消掉 谢谢)

**Comment by gao-sun** [comment]
yes, will fix tonight

**Comment by gao-sun** [comment]
please try v1.4.7

**Comment by mooxl** [comment]
Had the same problem, but after I updated to version 1.4.8, it was solved

**Comment by zxitedu** [comment]
@gao-sun This problem still exists. When the Eul is set to boot, this window will pop up after the computer is restarted. I am using Mac OS Big Sur 11.0.1(这个问题依旧存在是在将eul设置为开机自启动后 重启电脑就会弹出这个窗口 我使用的是Mac OS Big Sur 11.0.1)

**Comment by gao-sun** [comment]
taking a look

**Comment by gao-sun** [comment]
please try v1.5. let me know if it doesn't help.
