### ISSUE TITLE
CPU usage is getting higher

### ISSUE THREAD

**Issue by SinCheung** [gao-sun/eul#18]
As the usage time increases, the CPU usage of the app also continues to increase.
![image](https://user-images.githubusercontent.com/3352888/96665602-d6314d00-1387-11eb-8095-8d469c650b8b.png)

**Comment by korziee** [comment]
Beautiful app, but CPU usage for eul was regularly at 100% for around 5 minutes for me straight after installing.

**Comment by gao-sun** [comment]
Taking a look now

**Comment by gao-sun** [comment]
@SinCheung @korziee would you mind to provide your system version and device info? thanks

**Comment by gao-sun** [comment]
also, it'll be great to run with `--debug` option and see past a snippet of output here. say you have eul in `/Applications` folder, then open terminal and run `/Applications/eul.app/Contents/MacOS/eul --debug`

**Comment by SinCheung** [comment]
> @SinCheung @korziee would you mind to provide your system version and device info? thanks

MacBook Pro (15-inch, 2019) 10.15.6 (19G2021)

**Comment by zhqu1148980644** [comment]
nettop 总是占用130% 多的cpu

**Comment by gao-sun** [comment]
> nettop 总是占用130% 多的cpu

Noticed `nettop` has weird behaviors when running in background. Will change soon

**Comment by gao-sun** [comment]
please try to uncheck "Show network top activities" and see if helps, will replace `nettop` soon

![image](https://user-images.githubusercontent.com/14722250/97188158-2a9c5880-17de-11eb-8c74-554d3576dfed.png)

**Comment by zhqu1148980644** [comment]
Actually, I have no chance to set this option as nothing appears after I opened this program, only my mac's fans whirring.

version: 11.0 Beta (20A5384c)

**Comment by gao-sun** [comment]
> Actually, I have no chance to set this option as nothing appears after I opened this program, only my mac's fans whirring.
> 
> version: 11.0 Beta (20A5384c)

strange. I'll publish a new version to disable top activities by default

**Comment by gao-sun** [comment]
please remove `~/Library/Preferences/com.gaosun.eul.plist` and try v1.3.3 to see if it works. I'll replace `nettop` soon (#35)

**Comment by gao-sun** [comment]
I think another reason of this issue has been fixed in [this commit](https://github.com/gao-sun/eul/pull/99/commits/3a9918ee85badd5bac185f1ae1c69b814a32d75e), let me know if v1.4.5 works now. I'll close this issue for housekeeping if it has been fixed. thanks!

**Comment by zhqu1148980644** [comment]
it works now and no high CPU usage now.

**Comment by thebadpete** [comment]
Hi there, I am on v.1.5.13, MacOS Big Sur 11.2.1, MacBook Pro model MacBookPro15,1, I am still seeing high CPU, constantly 100%. I tried to turn off all top activities already. I really love the app but it is preventing me from making it an evergreen status bar item.

**Comment by gao-sun** [comment]
@thebadpete sorry missed your message. mind to take a look at [this comment](https://github.com/gao-sun/eul/issues/87#issuecomment-780158973) to see if it helps?
